sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t phenompeople/centos-sunjdk:8u144 jdk/8u144/

script:
  - docker run -it --rm phenompeople/centos-sunjdk:8u144 java -version